In [2]:
import numpy as np

## Datatypes and attributes in numpy

In [3]:
# The is only one datatype in numpy i.e. ndarray
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [4]:
type(a1)

numpy.ndarray

In [27]:
a2 = np.array([[1,2,3.5],
              [4,5,6.5],
              [7,8,9.7]])

a3 = np.array([[[1,2,3],
               [4,5,6],
               [7,8,9]],
              [[10,11,12],
              [13,14,15],
             [16,17,18]]])

In [28]:
a2


array([[1. , 2. , 3.5],
       [4. , 5. , 6.5],
       [7. , 8. , 9.7]])

In [29]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [21]:
a1.shape

(3,)

In [22]:
a2.shape

(3, 3)

In [23]:
a3.shape

(2, 3, 3)

In [25]:
# ndim to find out dimensions of the arrays
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [26]:
a1.size, a2.size, a3.size

(3, 9, 18)

###  Create a dataframe from numpy array

In [30]:
import pandas as pd

In [31]:
df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.5
1  4.0  5.0  6.5
2  7.0  8.0  9.7

## creating arrays 

In [3]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [6]:
ones = np.ones((100,20), dtype=int)

In [7]:
ones

array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1]])

In [8]:
range_array = np.arange(0,15,3)

In [9]:
range_array

array([ 0,  3,  6,  9, 12])

In [12]:
random_array = np.random.randint(0,100, size=(3,5))

In [13]:
random_array

array([[78, 85, 24, 10, 12],
       [10, 43, 62,  8, 27],
       [51, 37, 61, 88,  3]])

In [15]:
random_array_2 = np.random.random((5,3))
random_array_2

array([[0.83612979, 0.84588752, 0.59913306],
       [0.00243096, 0.67701676, 0.26097454],
       [0.37312501, 0.92849901, 0.0564795 ],
       [0.42415949, 0.036255  , 0.92014137],
       [0.27175005, 0.24867367, 0.43410325]])

In [18]:
random_array_3 = np.random.rand(4,5)
random_array_3

array([[0.87471705, 0.92649291, 0.69930684, 0.541885  , 0.33920777],
       [0.82363265, 0.15386568, 0.12481205, 0.17634453, 0.50827263],
       [0.8485894 , 0.02838999, 0.84823358, 0.43891121, 0.2935183 ],
       [0.50858943, 0.55775269, 0.57225684, 0.65566102, 0.24853513]])